import type { Metadata } from "next";
import { Cairo, El_Messiri } from "next/font/google";

import "./globals.css";

const cairo = Cairo({ subsets: ["latin", "arabic"], variable: "--font-cairo" });
const elMissiri = El_Messiri({
  subsets: ["latin", "arabic"],
  variable: "--font-el-missiri",
});

export const metadata: Metadata = {
  title: "shogol platform",
  description: "Generated by create next app",
};

import ReactQueryProvider from "@/providers/ReactQueryProvider";
import { Toaster } from "react-hot-toast";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ar" className={`${cairo.variable} ${elMissiri.variable}`}>
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
